language: ruby
cache: bundler
gemfile: Gemfile
script:
  - bundle exec jekyll serve
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.5.3